name: Build PPA source packages
on:
  push:
    branches:
      - v3
jobs:
  build:
    if: github.repository == 'canonical/go-dqlite'
    strategy:
      fail-fast: false
      matrix:
        target:
          - focal
          - jammy
          - noble
          - oracular
    runs-on: ubuntu-20.04
    environment:
      name: ppa
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: actions/checkout@v4
      with:
        repository: canonical/dqlite-ppa
        ref: go-dqlite-v3
        path: dqlite-ppa

    - name: Setup dependencies
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq debhelper devscripts dh-golang gnupg

    - name: Setup GPG signing key
      env:
          PPA_SECRET_KEY: ${{ secrets.PPA_SECRET_KEY }}
      run: |
          echo "$PPA_SECRET_KEY" > private-key.asc
          gpg --import --batch private-key.asc

    - name: Delete GPG signing key file
      if: always()
      run: |
          rm -f private-key.asc

    - name: Build source package
      env:
        DEBFULLNAME: "Github Actions"
        DEBEMAIL: "dqlitebot@lists.canonical.com"
        TARGET: ${{ matrix.target }}
      run: |
          cp -R dqlite-ppa/debian .
          go mod vendor
          VERSION="$(git describe --tags | sed -e "s/^v//" -e "s/-/+git/")"
          dch --create \
            --distribution ${TARGET} \
            --package go-dqlite-v3 \
            --newversion ${VERSION}~${TARGET}1 \
            "Automatic build from Github"
          debuild -S -sa -d -k${{ vars.PPA_PUBLIC_KEY }}

    - name: Upload to Launchpad
      run: |
          cd ..
          shopt -s globstar
          dput -U -u ppa:dqlite/dev **/*.changes
